### ISSUE TITLE
Can't get web SDK to work 

### ISSUE THREAD

**Issue by rpander93** [powersync-ja/powersync-web-sdk#16]
Hi,

I'm trying to implement the web SDK in a project, but it doesnt work for me. I just tried running the example-vite, but it doesnt seem to run.

![Screenshot 2024-01-09 at 12 01 54](https://github.com/powersync-ja/powersync-web-sdk/assets/1412227/05305683-1a9f-4e66-9d9e-de95f2d56232)

so the output from this line https://github.com/powersync-ja/powersync-web-sdk/blob/main/demos/example-vite/src/index.js#L31 isnt shown.

I'm using Firefox 121 on macOS 14.2. Also tried Chome, but that didnt work either

**Comment by DominicGBauer** [comment]
Hi @rpander93 did you run `pnpm build:packages` before running the vite example?

**Comment by rpander93** [comment]
Ah, missed that. If I do that and then `pnpm start` it works.

But, I cannot run it with `npm run dev`? So I need to re-build and preview everytime I make a change? It shows me:

<img width="1176" alt="Screenshot 2024-01-11 at 20 09 51" src="https://github.com/powersync-ja/powersync-web-sdk/assets/1412227/6ec3f009-4a16-4532-908d-89ff7b566898">

**Comment by kobiebotha** [comment]
`pnpm dev` should watch for changes using vite's development server - could you try that?

**Comment by kobiebotha** [comment]
Hmm no, that doesn't work - I'm getting a console error. I'll investigate ways to have a `watch` type of workflow and update here.

**Comment by xanderbarkhatov** [comment]
Here's my Vite config that works in dev.
Maybe it'll help.

```js
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  optimizeDeps: {
    exclude: ["@journeyapps/powersync-sdk-web"],
    include: [
      "object-hash",
      "uuid",
      "event-iterator",
      "js-logger",
      "lodash",
      "can-ndjson-stream",
    ],
  },
  worker: {
    format: "es",
  },
  build: {
    target: "ESNext",
  },
});
```

**Comment by rpander93** [comment]
> Here's my Vite config that works in dev. Maybe it'll help.
> 
> ```js
> import { defineConfig } from "vite";
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   optimizeDeps: {
>     exclude: ["@journeyapps/powersync-sdk-web"],
>     include: [
>       "object-hash",
>       "uuid",
>       "event-iterator",
>       "js-logger",
>       "lodash",
>       "can-ndjson-stream",
>     ],
>   },
>   worker: {
>     format: "es",
>   },
>   build: {
>     target: "ESNext",
>   },
> });
> ```

Copy-pasting this in the example project doesnt work for me. Same error :(

**Comment by xanderbarkhatov** [comment]
@rpander93 

https://github.com/xanderbarkhatov/powersync-vite-demo

Here's the same working demo.

For pnpm you also need an .npmrc file with `shamefully-hoist=true`

**Comment by rpander93** [comment]
that works. thanks!
